#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

rm 0/include/controlProperties
rm 0/include/transportProperties
rm 0/include/Results

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase


# ----------------------------------------------------------------- end-of-file
