#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

ln constant/controlProperties 0/include/controlProperties
ln constant/transportProperties 0/include/transportProperties
ln constant/Results 0/include/Results

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

setResults()
{
	value=$(sed -En 's/startPot[[:blank:]]+//p' constant/controlProperties | sed 's/;.*//') 
	sed -E '/Vcell/s/[^[:blank:]]+$/'"$value;"/ -i constant/Results
}


runApplication blockMesh

#Set dictionaries
setResults

#runApplication setFields

#-- Run on single processor
runApplication `getApplication`

## Decompose
#for i in bottomAir topAir heater leftSolid rightSolid
#do
#   decomposePar -region $i > log.decomposePar.$i 2>&1
#done
#
## Run
#runParallel `getApplication` 4
#
## Reconstruct
#for i in bottomAir topAir heater leftSolid rightSolid
#do
#   reconstructPar -region $i > log.reconstructPar.$i 2>&1
#done


postProcess -func totalCurrentDensity -latestTime
postProcess -func partialCurrentDensity -latestTime

#echo "    postProcess -func 'grad(U)'"
#echo
#echo "creating files for paraview post-processing"
#echo
#paraFoam #-touchAll

# ----------------------------------------------------------------- end-of-file
